apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer # Creates a Google Cloud Load Balancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80